apiVersion: v1
kind: Service
metadata:
  name: dev-generator-service
  labels:
    app: dev-generator-service
spec:
  type: NodePort
  ports:
    - port: 123
      targetPort: 123
  selector:
    app: dev-generator-service
